// #define UNICODE_SONG_OSX  COIN_SOUND
// #define UNICODE_SONG_LNX  UNICODE_LINUX
// #define UNICODE_SONG_BSD  MARIO_GAMEOVER
// #define UNICODE_SONG_WIN  UNICODE_WINDOWS
// #define UNICODE_SONG_WINC UNICODE_WINDOWS
//
#define UNICODE_SELECTED_MODES UC_LNX, UC_WIN, UC_WINC, UC_OSX

#undef RGBLED_NUM
#define RGBLED_NUM 4
// #define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_ALTERNATING
// #define RGBLIGHT_MODE_RAINBOW_SWIRL
// #define RGBLIGHT_MODE_BREATHING
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_SLEEP


#ifndef NO_DEBUG
#define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT
#endif // !NO_PRINTBUG
